@hostname = 127.0.0.1:5000

### Get Status
GET http://{{hostname}}/api/status
Accept: application/json

### Load Model
PUT http://{{hostname}}/api/models
Accept: application/json
Content-Type: application/json

{
    "model_key": "crumb_-_nano-mistral"
}

### Unload Model
DELETE http://{{hostname}}/api/models
Accept: application/json
Content-Type: application/json

{
    "model_key": "crumb_-_nano-mistral"
}

### Create Session
# @name create_debug_session
POST http://{{hostname}}/api/session/debug
Accept: application/json
Content-Type: application/json

### Set session model
PUT http://{{hostname}}/api/session/{{create_debug_session.response.body.session_id}}/models
Accept: application/json
Content-Type: application/json

{
    "model_key": "crumb_-_nano-mistral"
}

### GET session model
GET http://{{hostname}}/api/session/{{create_debug_session.response.body.session_id}}/models
Accept: application/json
Content-Type: application/json

### Request SSE
GET http://{{hostname}}/api/session/{{create_debug_session.response.body.session_id}}/chat/stream
Accept: application/json

### Send Message
POST http://{{hostname}}/api/session/{{create_debug_session.response.body.session_id}}/chat
Accept: application/json
Content-Type: application/json

{
    "message": "Hello!"
}